/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as ReplayDevRouteImport } from './routes/replay-dev'
import { Route as TherapistRouteImport } from './routes/therapist'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayDevRoute = ReplayDevRouteImport.update({
  id: '/replay-dev',
  path: '/replay-dev',
  getParentRoute: () => rootRouteImport,
} as any)
const TherapistRoute = TherapistRouteImport.update({
  id: '/therapist',
  path: '/therapist',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/patient': typeof PatientRoute
  '/replay-dev': typeof ReplayDevRoute
  '/therapist': typeof TherapistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/patient': typeof PatientRoute
  '/replay-dev': typeof ReplayDevRoute
  '/therapist': typeof TherapistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/patient': typeof PatientRoute
  '/replay-dev': typeof ReplayDevRoute
  '/therapist': typeof TherapistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/patient' | '/replay-dev' | '/therapist'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/patient' | '/replay-dev' | '/therapist'
  id: '__root__' | '/' | '/patient' | '/replay-dev' | '/therapist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PatientRoute: typeof PatientRoute
  ReplayDevRoute: typeof ReplayDevRoute
  TherapistRoute: typeof TherapistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay-dev': {
      id: '/replay-dev'
      path: '/replay-dev'
      fullPath: '/replay-dev'
      preLoaderRoute: typeof ReplayDevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/therapist': {
      id: '/therapist'
      path: '/therapist'
      fullPath: '/therapist'
      preLoaderRoute: typeof TherapistRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PatientRoute: PatientRoute,
  ReplayDevRoute: ReplayDevRoute,
  TherapistRoute: TherapistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
